stages:
  get_data:
    cmd: python get_data.py
    outs:
      - data/titanic_raw.csv

  preprocess:
    cmd: python preprocess.py
    deps:
      - data/titanic_raw.csv
      - preprocess.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed/train.csv
      - data/processed/test.csv
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false
